### ISSUE TITLE
What's the difference in the coordinates in Flame components

### ISSUE THREAD

**Issue by spkingr** [luanpotter/flame#15]
When I make the little game, I am confused with the different coordinates in the widgets or components:

1. Is the stage(phone) width/height equatable to the viewport's width/height in Box2dComponent? So does the dimension from `Flame.util.initialDimensions()` ?
2. Where is the origin in the body in `Box2dComponents` when specifys the `BodyDef` in `_createBody`? Actually it is a `Vector2` value: 
```
final bodyDef = new BodyDef();
bodyDef.position = new Vector2(0.0, -24.0);
```
3. Move the sprite is the same work as the `BodyComponent`? Use the `body.position` in components?
4. How to paint the texture to the right location? (Maybe the same location with the box2d body. I think.)

Thanks very much for helping!

**Comment by feroult** [comment]
@spkingr Hi there.

I can explain the coordinate system in more depth later.

But basically, the Box2D coordinate system uses the point (0, 0) as the center of the screen. Left and Bottom positions are negative x or y values.

The total world dimension is something that I've made some changes last days. Right now, you need to set the desired dimensions through the constructor when creating your Box2DComponent. For instance you can get the return from `Flame.util.initialDimensions()` to set a FullScreen world.

Remember that you can also set the Scale of World and all body dimensions will be multiplied by this factor.

To move bodies you'll need to use the Box2D world mechanics.

To check how to render textures and other things, you can also check it out this example box2d game I'm working on: https://github.com/feroult/haunt

If you try to run it, remember to change the Flame dependency in `pubspec.yaml`, 'cause I'm using a local checkout reference.

**Comment by spkingr** [comment]
@feroult  Thanks very much, and I have already cloned your sweet haunt game to play with, and the questions are brought out just because of the digitals in your game code, such as 6.2 as `height`, -16 as the box `y` position.
But now, with your explanations, I have ready got a lot! Thanks again and I will get it a try! :)
