### ISSUE TITLE
Ho Ho Ho! 

### ISSUE THREAD

**Issue by feroult** [luanpotter/flame#27]
Merry Christmas Flame Fellows! 🎅 🎄🎄🎄🎄

Santa Claus is asking which features we'd like to have on Flame next year

Make your wish list here, and let's see what happens next :))  🎁🎁🎁

**Comment by erickzanardo** [comment]
- Full gamepad support (currently only android is supported and there is no support for the analog sticks)
- Keyboard support (but needs to check if flutter is ready for this)

**Comment by luanpotter** [comment]
* Desktop Support (using Flutter for Desktop, now being worked on on v1.0)

**Comment by erickzanardo** [comment]
- add native support for commonly used by the gamede community, like tiled for example

**Comment by feroult** [comment]
> * add native support for commonly used by the gamede community, like tiled for example

I think it will be nice to work on that. It looks like some [already started to support TMX](https://github.com/radicaled/tmx.dart) files 4 years ago :)

I played a little bit with this lib and it seems to be well written... I'm in contact with the owner.

Huh, Santa has listen to one wish 🎁

**Comment by Panthro** [comment]
- Update the documentation. :-P I'm a heavy flutter developer, but new to flame, currently having a hard time to a hello world!

**Comment by erickzanardo** [comment]
@Panthro could you list the issues you had with the documentation, so we can be more assertive improving it where it lacks information?

**Comment by Panthro** [comment]
@erickzanardo From my point of view, looks like you guys are heavy game developers that are porting something you know very well to flutter. This makes the documentation expecting a lot of knowledge from guys like me that has never developed a gameLoop aware game in my life try to tear my eyes and throw them out of the window when I can't make things like a background continuously tile.

The examples pointed out are either too simple (a box without a background that explodes in it's own position), or too complex (everything separated in their own components with a lot of functionality inside each component that I don't understand).

Things I missed the most int he documentation:

- WTF is the camera and how do y play with it? (now I kinda understand, but was about 2-3 hours banging my head against the wall and playing with numbers to understand it).
- How to add a Flame Game inside an app with other widgets, currently dealing with that and having a hard time.
- There are several of the examples of the documentation like the `handleTap` method that was mentioned somewhere which does not exists in the baseGame (or was created in another class).
- What all the different ways of painting and interacting with the canvas? I know this seems basic to game developers, but that was the first time I actually painted on the canvas by myself on a flutter app :-)

To be more assertive:
Examples and documentation would be more self explanatory, without interdependencies. Think about this, when we're new to an API, we don't know which methods are native to the api and which ones are not, so creating new methods for the example confuses newcomers.

**Comment by Panthro** [comment]
BTW, amazing work on abstracting a lot of things to a non regular game developer, just realised you guys are from 🇧🇷as well, me too :-) 

Obrigado pela ferramenta.

**Comment by erickzanardo** [comment]
I see, indeed we could add some tutorials to the docs, maybe some step by step examples to help who never developed games and chose flame as its starting tool in the gamedev life.

Sadly this is kind of a lot of work and I don't know when we will be able to do that, so I created an [issue](https://github.com/luanpotter/flame/issues/31) here so we don't forgot about it and you can keep track of the progress of the tutorials.

In the meantime also feel free to ask questions about it, we will try to help whenever we can, if you like and use discord join our server, there is a channel dedicated to flame there: https://discord.gg/jzM7vPP

Also happy to see a fellow countryman here o/
