### ISSUE TITLE
Add more tutorials step-by-step

### ISSUE THREAD

**Issue by erickzanardo** [luanpotter/flame#31]
We should add more tutorials step-by-step on how to use the components of flame, focusing on people who never developed games and has chose Flame to start.

Tutorial example:

 - Basic project startup
 - Handle input
 - Images and rendering things
 - Camera
 - etc

If anyone feels the need of other tutorials, just comment here on this issue

**Comment by feroult** [comment]
I have 2 ideias for this:

*  Provide a `examples` folder collecting different games and complexity
* and/or create a complete gallery game with different show cases.

**Comment by erickzanardo** [comment]
@feroult I like both ideas, but I think this could be complemented by some step-by-step tutorials, like the [unity](tutorials for example: https://unity3d.com/pt/learn/tutorials), they really help people getting started with Unity

**Comment by arcanosam** [comment]
I consider myself totally newbie in this days of game programming.

I would to see notions about how to understand metrics, proportion, building a scene,  export 3d models, using blendrr for example

**Comment by erickzanardo** [comment]
So, checking the README again, there is already a good [QuickStart tutorial](https://medium.com/@luanpotter27/a-comprehensive-flame-tutorial-or-how-to-make-games-with-flutter-74f22c4ecbfa) that covers a lot of the basics.

Some topics that we can still create tutorials about are:

- Camera
- Box2d
- Background handling
- GamePad usage

Anything else I am missing @luanpotter ?

**Comment by luanpotter** [comment]
I'd also like to have more examples, I thought about having a collection of small, very dedicated example showcasing specific features. I started working on that on our new release branch (0.10.0), but still needs more work as well.

**Comment by Arham4** [comment]
I'm confused as to why Github's wiki isn't being utilized for this. [LibGDX](https://github.com/libgdx/libgdx/wiki/) does so beautifully, I don't see why the same isn't done here. Perhaps a beginning to this issue hasn't been initialized, but an index page would be a great start surely.

**Comment by erickzanardo** [comment]
Closing this issue in favor to separate issues per feature, please, feel free to open a new issue in case that you find something that needs documentation, and still does not have an issue for it.
