### ISSUE TITLE
Method for terminating Game

### ISSUE THREAD

**Issue by Joseph-W-E** [luanpotter/flame#4]
Hello. I'm really enjoying working with flame, and am actively building a game for a class of mine.

I was wondering if there was a way to "destroy" a `Game`, in that I can successfully terminate a `Game` after I've invoked `.start()`?

I imagine something like `myGame.stop();` for terminating the window rendering loop would be helpful for transitioning between Flutter widgets (for main screen handling / other Flutter stuff).

I would make a pull request, and might soon, but I'm not 100% sure how to avoid a constant assertion exception

```
E/flutter ( 9921): 'package:flutter/src/scheduler/binding.dart': Failed assertion: line 643 pos 12: '_schedulerPhase == SchedulerPhase.midFrameMicrotasks': is not true.
E/flutter ( 9921): #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
E/flutter ( 9921): #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
E/flutter ( 9921): #2      BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:643:12)
E/flutter ( 9921): #3      _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:91)
E/flutter ( 9921): #4      _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:80)
```

**Comment by Joseph-W-E** [comment]
I've taken a stab at allowing transitioning between flutter widgets and the game scene:
https://github.com/Joseph-W-E/flame/commit/5dfa97a07ded97b6a570ee477d106bfd01af27d7
There's still infinite exceptions thrown, but for this being a class project that's due soon, I'm going to shamefully pretend they don't exist.

**Comment by feroult** [comment]
Hi @Joseph-W-E 

Great you are enjoying Flame!

Would you please explain the specific use case where you need to transition to Flutter widgets?

We've been discussing about this, it would be great to understand your needs.

Regards

**Comment by Joseph-W-E** [comment]
Sure thing. https://github.com/Joseph-W-E/angry_arrows is a project I'm working on for fun / class. Basically, the class is an Android specific class, but we are allowed to use Flutter under the guise that we demonstrate how Flutter's UI architecture differ from Android's. To have some fun with this, we (my friend and I) are making a simple game that has two parts:

1. The home screen / main menu
    - this is done using Flutter Widgets
    - a button callback can invoke `loadGameScene()` to kick off the game engine (this is where `flame` comes in)
2. The game engine
    - done using `flame`
    - a very simple game (launch arrows into crates)
    - the game has a "back button" that invokes a callback (brings us back to Flutter Widgets)

The reason we want to use Flutter widgets
1. for class, obviously
2. much easier for building a pretty / interactive UI for the game

**Comment by luanpotter** [comment]
This is a very important use case and one we definitely intend to support. Currently, as @feroult mentioned, there has been some discussion but we didn't find a clear-cut best way to do it. In fact, we ought to rework the whole ServiceBinding strategy because of the supermixins issue.

I'll definitely take a look at your code soon, and if we can fix all the exceptions, we can PR you :))

Thanks for your input!

**Comment by Joseph-W-E** [comment]
Sounds good! For what it's worth, here's my solution thus far. I've gotten rid of the exceptions happening on each frame, and have finally reached a bandaid solution good enough for this little project.

https://github.com/Joseph-W-E/flame/pull/1/files?diff=split

**Comment by luanpotter** [comment]
I have 0.8.0 which fixes this issue! @Joseph-W-E, see if the solutions fits your needs :)

**Comment by luanpotter** [comment]
This was no longer an issue on our tests, and the systems are very well integrated.

Feel free to open a new issue if you encounter any problem whatsoever, we'd love to help :)
