### ISSUE TITLE
Drawing sprites on iOS

### ISSUE THREAD

**Issue by p3e7** [luanpotter/flame#7]
Hi, today I had some time to test your engine an I really appreciate the effort, but I ran into a problem. 
If I use the old version 6.2 I can easily draw sprites, but with version 8.1 nothing happens.
I tried all documentation hints and tutorials I could find.

**Comment by p3e7** [comment]
I'm sorry, I assigned the sprite in the render method... my bad...

**Comment by luanpotter** [comment]
Indeed, the sprite loads asynchronously when created, so if you re-assign every render method to a new instance, it will never finish loading to be rendered. Your code should look something like this:

```dart
  // constructor
  Sprite sprite = new Sprite('player.png'); // starts loading the sprite
  this.myObj = new SpriteComponent.fromSprite(64.0, 64.0, sprite);

 // render
 this.myObj.render(canvas); // render will do nothing until the sprite is loaded
```

Also, consider using the new `BaseGame` in `0.8.x`, as it deals with rendering and updating for you (simply add your components to the array via the `add` method.

I'm glad your are having progress with flame, if you have any more questions or suggestions, feel free to ask :)
