### ISSUE TITLE
Add readme notice for stable channel

### ISSUE THREAD

**Issue by impulse** [luanpotter/flame#76]
Adding flame >=0.10.3 to pubspec while using the stable channel results in following error.
> Because app depends on flame >=0.2.0 <0.9.2 which requires SDK version >=1.8.0 <2.0.0 or >=2.0.0-dev.50.0 <2.0.0, version solving failed.

There should probably be a notice that using the latest version requires switching to master/dev channel.

**Comment by feroult** [comment]
I was discussing with @luan and @erickzanardo ... 

I all agree to make `flame` depend on `flutter` stable.

We're making this change...

**Comment by erickzanardo** [comment]
Yes, this may be included on the next release.

**Comment by luanpotter** [comment]
I agree; @feroult , if you could please add a PR for that. Depending on how long this might take, we can add a small disclaimer to the readme as well until then.

**Comment by luanpotter** [comment]
Just added that for now, but we should really accept stable, at least as soon as they release the fix for the ImageRecorder thingy.

So I'm closing this (see 6f68ff7c102a681c2ba77428d28b3bda9ade9952).
