### ISSUE TITLE
Using the Parallax Component as described in the docs results in an dart(new_with_abstract_class) error

### ISSUE THREAD

**Issue by AnorakRPO** [luanpotter/flame#77]
The docs state to create a new instance of ParallaxComponent, which results in an `dart(new_with_abstract_class)` error.

https://github.com/luanpotter/flame/blob/master/doc/components.md

Abstract classes have to be extended like

> class MyParallaxBG extends ParallaxComponent {
> }

**Comment by luanpotter** [comment]
@feroult IIRC, one needed to subclass ParallaxComponent to specify some details, right? I think the docs might be incorrect, @AnorakRPO . Thanks for the notice :)

**Comment by luanpotter** [comment]
@feroult can you take a look into this? I believe we can improve the docs a bit :)

**Comment by erickzanardo** [comment]
@luanpotter We fixed that on the last version, Parallax Component is not abstract anymore

**Comment by luanpotter** [comment]
Ok, so this can be closed, right?

**Comment by erickzanardo** [comment]
Sure
