### ISSUE TITLE
Powered by Flame badge

### ISSUE THREAD

**Issue by impulse** [luanpotter/flame#82]
Add a Flame badge to the README so people can show that they use flame.
I would suggest one of the following:

[![Powered by Flame](https://img.shields.io/badge/Powered%20by-%F0%9F%94%A5-orange.svg)](https://flame-engine.org)
[![Powered by Flame](https://img.shields.io/badge/Powered%20by-%F0%9F%94%A5-orange.svg?style=flat-square)](https://flame-engine.org)
[![Powered by Flame](https://img.shields.io/badge/Powered%20by-%F0%9F%94%A5-orange.svg?style=for-the-badge)](https://flame-engine.org)

**Comment by erickzanardo** [comment]
That is a very cool idea @impulse, @renancaraujo can take care of this?

**Comment by renancaraujo** [comment]
Yes sir

**Comment by luanpotter** [comment]
I love it!

**Comment by erickzanardo** [comment]
Any news on this @renancaraujo ?

**Comment by renancaraujo** [comment]
Waiting promise to resolve.

**Comment by impulse** [comment]
Added in #95
