### ISSUE TITLE
Incorrect toRect() Rect in PositionComponent when using non default topleft anchor

### ISSUE THREAD

**Issue by illiapoplawski** [luanpotter/flame#97]
`Rect toRect() => Rect.fromLTWH(x, y, width, height);`
does not take into account the offset introduced when using a non default anchor leading to a rect that is not in the same place as the component.

Instead it should use the relative position variable from the anchor to calculate the correct rect such as:
`Rect toRect() => Rect.fromLTWH(x - anchor.relativePosition.dx * width, y - anchor.relativePosition.dy * height, width, height);`

**Comment by luanpotter** [comment]
Agreed, that's a confusing behaviour . Would you like to help us out with a pr? Should be a minor fix

**Comment by erickzanardo** [comment]
Fixed by #98  and #99
